
module.exports = [
    { name: 'guangdong', value: '广东' },
    { name: 'beijing', value: '北京' },
    { name: 'tianjin', value: '天津' },
    { name: 'hebei', value: '河北' },
    { name: 'liaoning', value: '辽宁' },
    { name: 'jilin', value: '吉林' },
    { name: 'heilongjiang', value: '黑龙江' },
    { name: 'shandong', value: '山东' },
    { name: 'jiangsu', value: '江苏' },
    { name: 'shanghai', value: '上海' },
    { name: 'zhejiang', value: '浙江' },
    { name: 'anhui', value: '安徽' },
    { name: 'fujian', value: '福建' },
    { name: 'jiangxi', value: '江西' },
    { name: 'guangxi', value: '广西' },
    { name: 'hainan', value: '海南' },
    { name: 'henan', value: '河南' },
    { name: 'hunan', value: '湖南' },
    { name: 'hubei', value: '湖北' },
    { name: 'shanxi', value: '山西' },
    { name: 'neimenggu', value: '内蒙古' },
    { name: 'ningxia', value: '宁夏' },
    { name: 'qinghai', value: '青海' },
    { name: 'gansu', value: '甘肃' },
    { name: 'xinjiang', value: '新疆' },
    { name: 'sichuan', value: '四川' },
    { name: 'guizhou', value: '贵州' },
    { name: 'yunnan', value: '云南' },
    { name: 'chongqing', value: '重庆' },
    { name: 'xizang', value: '西藏' },
    { name: 'hongkong', value: '香港' },
    { name: 'aomen', value: '澳门' },
    { name: 'taiwan', value: '台湾' }
  ]