
module.exports = [
    { en_name: 'guangdong', name: '广东' },
    { en_name: 'beijing', name: '北京' },
    { en_name: 'tianjin', name: '天津' },
    { en_name: 'hebei', name: '河北' },
    { en_name: 'liaoning', name: '辽宁' },
    { en_name: 'jilin', name: '吉林' },
    { en_name: 'heilongjiang', name: '黑龙江' },
    { en_name: 'shandong', name: '山东' },
    { en_name: 'jiangsu', name: '江苏' },
    { en_name: 'shanghai', name: '上海' },
    { en_name: 'zhejiang', name: '浙江' },
    { en_name: 'anhui', name: '安徽' },
    { en_name: 'fujian', name: '福建' },
    { en_name: 'jiangxi', name: '江西' },
    { en_name: 'guangxi', name: '广西' },
    { en_name: 'hainan', name: '海南' },
    { en_name: 'henan', name: '河南' },
    { en_name: 'hunan', name: '湖南' },
    { en_name: 'shanxi2', name: '陕西' },
    { en_name: 'hubei', name: '湖北' },
    { en_name: 'shanxi1', name: '山西' },
    { en_name: 'neimenggu', name: '内蒙古' },
    { en_name: 'ningxia', name: '宁夏' },
    { en_name: 'qinghai', name: '青海' },
    { en_name: 'gansu', name: '甘肃' },
    { en_name: 'xinjiang', name: '新疆' },
    { en_name: 'sichuan', name: '四川' },
    { en_name: 'guizhou', name: '贵州' },
    { en_name: 'yunnan', name: '云南' },
    { en_name: 'chongqing', name: '重庆' },
    { en_name: 'xizang', name: '西藏' },
    { en_name: 'hongkong', name: '香港' },
    { en_name: 'aomen', name: '澳门' },
    { en_name: 'taiwan', name: '台湾' }
  ]